random_subset method for bitsets
mrc-ide/individual pull request #111
Opened 2021-06-16 23:20 UTC by slwu89

This PR should address #104 with a new method `random_subset`; there is not a ton of checking done at the R level because `Rcpp::sample` gives pretty informative error messages for bad inputs.

Still happy to change the method name if we come up with something better. `choose` is one option, since it brings to mind the binomial "n choose k".

2021-06-17 07:15 UTC, giovannic requested changes
I quite like `choose` actually! It's up to you :)

2021-06-17 07:15 UTC, giovannic commented on tests/testthat/test-bitset.R
> +  expect_equal(b$random_subset(5)$size(), 5)
```suggestion
  expect_equal(b$random_subset(5)$size(), 5)
  expect_equal(b$copy()$or(b$copy()$random_subset(5))$to_vector(), b$to_vector()) # check that b$random_subset is a subset of b
```

2021-06-17 15:47 UTC, slwu89 commented on tests/testthat/test-bitset.R
> +  expect_equal(b$random_subset(5)$size(), 5)
added this test! thanks, that was a good catch. Also renamed `random_subset` -> `choose`, I think it's the most descriptive so far.

2021-06-21 08:11 UTC, giovannic approved these changes

2021-06-21 08:11 UTC, merged