updates to events, fixes to avoid undefined behavior
mrc-ide/individual pull request #139
Opened 2021-08-16 03:44 UTC by slwu89

This PR addresses #138 as well as making other changes to the events.

1. class methods for `Event` and `TargetedEvent` are defined outside of the class in inst/include/Event.h
2. add checks for input in R/targeted_event.R to avoid undefined behavior; specifically check for positive, finite input for arguments that will be coerced to `vector<size_t>` by Rcpp (to avoid CRAN UBSCAN errors).
3. add new method overload to `TargetedEvent::schedule` taking a bitset and vector of delays, so that a cohort with unique delay values can be scheduled without converting it to vector first.
4. add new function `round_double` to inst/include/Event.h that checks an input double is positive and finite before rounding and casting to `size_t`; now `round_delay` calls this internally. This helps users because when strange delays (`Inf`,etc) get passed, a more informative error message is printed.
5. in `event.cpp` when inserting into a bitset from a vector (where there is the possibility of the vector having bad values outside the range of the bitset), use `insert_safe` instead of `insert` to produce more informative error messages (this may be related to #35?)
6. split `test-event.R` into 2 files, `test-event.R` and `test-targetedevent.R`; add many tests to catch corner cases that were not getting tested for targeted events.
7. For all types that can accept the `index` argument as a vector (`TargetedEvent`, `CategoricalVariable`, `IntegerVariable`, `DoubleVariable`), consistently check for positive, finite input before passing to C++ to avoid undefined behavior if values outside of the representable range of `size_t` type get passed (same as 2 but for all objects that might suffer from this problem).

I also bumped the version number and updated NEWS.md. Not sure what you think about updating the version @giovannic, none of the items here are especially urgent, but they were lingering things I wanted to get to. I checked this branch for undefined behavior and/or memory leaks using the docker container in Rich's blog post and confirmed none of either before submitting this PR.

2021-08-19 09:05 UTC, giovannic requested changes
Thank you, thank you, thank you

2021-08-19 09:05 UTC, giovannic commented on inst/include/Event.h
> +    auto not_target = ~target;
I really regret making `~` the inverse operator for bitsets. Since it makes me think of destructors. It's out of scope for this though, so I've made an issue #141

2021-08-19 09:05 UTC, giovannic commented on tests/testthat/test-events.R
> -  event$schedule(c(2, 4), 1.9)
It would still be nice to check/show that the discretisation of time is intentional and works as expected

2021-08-19 22:10 UTC, slwu89 commented on R/double_variable.R
> +        double_variable_get_values(self$.variable)
addressed in https://github.com/mrc-ide/individual/pull/139/commits/396c7ec420801f5b57374d9a29acf9ca11dbf175

2021-08-19 22:10 UTC, slwu89 commented on R/double_variable.R
> +          double_variable_get_values_at_index(self$.variable, index$.bitset)
addressed in https://github.com/mrc-ide/individual/pull/139/commits/396c7ec420801f5b57374d9a29acf9ca11dbf175

2021-08-19 22:10 UTC, slwu89 commented on R/double_variable.R
> +          double_variable_get_values_at_index_vector(self$.variable, index)
addressed in https://github.com/mrc-ide/individual/pull/139/commits/396c7ec420801f5b57374d9a29acf9ca11dbf175

2021-08-19 22:11 UTC, slwu89 commented on R/integer_variable.R
> +        integer_variable_get_values(self$.variable)
addressed in https://github.com/mrc-ide/individual/pull/139/commits/396c7ec420801f5b57374d9a29acf9ca11dbf175

2021-08-19 22:11 UTC, slwu89 commented on R/integer_variable.R
> +          integer_variable_get_values_at_index(self$.variable, index$.bitset)
addressed in https://github.com/mrc-ide/individual/pull/139/commits/396c7ec420801f5b57374d9a29acf9ca11dbf175

2021-08-19 22:11 UTC, slwu89 commented on R/integer_variable.R
> +          integer_variable_get_values_at_index_vector(self$.variable, index)
addressed in https://github.com/mrc-ide/individual/pull/139/commits/396c7ec420801f5b57374d9a29acf9ca11dbf175

2021-08-19 22:11 UTC, slwu89 commented on inst/include/Event.h
> +            ++bitset_it;
thanks!

2021-08-19 22:12 UTC, slwu89 commented on tests/testthat/test-events.R
> -  event$schedule(c(2, 4), 1.9)
addressed in https://github.com/mrc-ide/individual/pull/139/commits/396c7ec420801f5b57374d9a29acf9ca11dbf175

2021-08-20 08:18 UTC, giovannic approved these changes
👍

2021-08-20 08:18 UTC, merged