Feat/resizable
mrc-ide/individual pull request #159
Opened 2021-11-12 15:08 UTC by giovannic

Some simulations require dynamic population sizes, this is a start at implementing that support. Hopefully the first of three pull requests for resizeable variables (Double, Integer and Categorical). This one is just for ResizeableDoubleVariable.

ResizeableDoubleVariable allows clients to queue "extentions" and "shrinks", which will be applied after normal updates. 

Extentions will add new individuals with an initial value. e.g.

```r
age$queue_extend(rep(0, n_births))
```

It can be used to model births or importation in a population.

Shrinks can selectively remove individuals from a variable, using either a bitset or a variable. e.g.

```r
age$queue_shrink(deaths)
```

It can be used to model death-like processes in a population.

Notable Changes:

 * Consolidated filtering algorithm (from bitset_filter) into FilterIterator, so that it can be used with any iterables
 * New C++ classes, C++ interface and R6 objects for ResizeableDoubleVariable
 * Inheritance-based resizing updates

2021-11-14 20:38 UTC, slwu89 requested changes
@giovannic this looks good, I just have a few comments.

2021-11-14 20:38 UTC, slwu89 commented on R/resizeable_double.R
> +#' @title DoubleVariable Class
Can you update the `DoubleVariable` to `ResizeableDoubleVariable` in the class docs?

2021-11-14 20:38 UTC, slwu89 commented on R/resizeable_double.R
> +#' @description Represents a continuous variable for an individual.
It would be nice to give the update order, i.e. when are resizing updates applied, so users can structure processes correctly.

2021-11-14 20:38 UTC, slwu89 commented on src/utils.h
> -#ifndef UTILS_H_
perhaps we can move this code to inst/include/utils.h?

2021-11-16 15:55 UTC, giovannic commented on R/resizeable_double.R
> +#' @description Represents a continuous variable for an individual.
Done. I'll add a vignette at the end of this epic too

2021-11-16 16:36 UTC, slwu89 commented on R/resizeable_double.R
> +#' @description Represents a continuous variable for an individual.
oh no not jira

2021-11-16 16:42 UTC, slwu89 commented on R/resizeable_double.R
> +          if (index$size() > 0){
Sorry, I didn't catch this on the last review. I think we want to check here to make sure the bitset max size is the same as the variable size, the changes I made in #156. You might do it in the cpp but it would be nice to have it standardized across variable types. I check at the R level for "variable reset" and "subset update with bitset" type updates: https://github.com/mrc-ide/individual/blob/dev/R/double_variable.R#L74

2021-11-16 16:42 UTC, slwu89 commented on src/utils.h
> -#ifndef UTILS_H_
sounds good.

2021-12-18 18:56 UTC, slwu89 reviewed
Hi @giovannic, sorry it took me so long to get to this. I looked everything over, it looks great, I like the pimpl-style thing you have going on with the R6 variable classes.

2021-12-21 10:42 UTC, merged