Speedup render by avoiding repeated vector copies.
mrc-ide/individual pull request #176
Opened 2023-12-21 14:56 UTC by plietar

The `Render$render` method is used throughout a simulation to store data that needs outputting at the end. It does so by creating a vector per metric, large enough to fit all timesteps.

Unfortunately, each time the `render` method is called, the assignment into the vector actually creates a new copy, instead of modifying it in-place. For long simulations (ie. tens of thousands of timesteps), these vectors are both fairly large and get copied over and over again at each timestep, to the point where the `render` method dominates the execution time.

The core of the problem can easily be reproduced by recreating the same conditions of the `Render` class, using a vector stored inside of an environment:

```r
e <- new.env(parent=emptyenv())
e$vector = rep(0, 10)
tracemem(e$vector)
# [1] "<0x56313d8a4c80>"
e$vector[[0]] <- 1
# tracemem[0x56313d8a4c80 -> 0x56314180ff60]:
e$vector[[1]] <- 1
# tracemem[0x56314180ff60 -> 0x563141613fc0]:
e$vector[[2]] <- 1
# tracemem[0x563141613fc0 -> 0x563141984b10]:
```

Here `e` mirrors the `private` environment of the `Render` class, as it would be constructed by R6. The `tracemem` call is used to trace copies of the vector. Each subsequent assignment to the vector creates a new copy of it, which can be seen as tracemem lines in the console.

I did experiment with ways of avoiding the copies without resorting to C++ code, but I couldn't find anything that wasn't made of horrible hacks.

The patch here fixes this issue by creating a C++ class, that acts as a thin wrapper around a vector. Thanks to this indirection, the vector is guarateed to have reference semantics and be modified in-place. A method exists on the wrapper class to extract the underlying vector. This does incur a copy, but is only expected to be called once (per vector), at the end of the simulation.

For large runs, this change has a dramatic effect of the performance of the end-to-end simulation. Using malariasimulation as a benchmark:
```r
# Before the change
system.time(run_simulation(timesteps = 50000))
#    user  system elapsed
# 334.662   0.604 335.253

# Afterwards
system.time(run_simulation(timesteps = 50000))
#    user  system elapsed
# 134.270   0.008 134.271
```

The impact is much less noticeable are shorter runs, since the vectors being copied are much smaller (on the order of 20% improvement for a 10'000 time steps run, 5% for 5'000 time steps).

2023-12-21 15:02 UTC, richfitz requested changes

2023-12-21 15:02 UTC, richfitz commented on src/render_vector.cpp
> +    return Rcpp::XPtr<RenderVector>(new RenderVector(data), true);
I am not 100% sure about the semantics here of saving a `Rcpp::NumericVector` within an `XPtr`; this might work but might also be something that bites us later. My inclination would have been to use `std::vector<double>` for the storage behind the pointer and dump into `Rcpp::NumericVector` on export (so definitely one copy but also no risk of later in-place mutation)

2023-12-21 21:42 UTC, plietar commented on src/render_vector.cpp
> +void render_vector_update(Rcpp::XPtr<RenderVector> v, size_t index, float value) {
Yep. Thanks.

2023-12-21 21:42 UTC, plietar commented on R/render.R
> +      private$.vectors[[name]] = create_render_vector(rep(value, private$.timesteps))
Sure. Done.

2023-12-21 21:42 UTC, plietar commented on R/render.R
> +        private$.vectors[[name]] = create_render_vector(rep(NA, private$.timesteps))
Applied the suggestion.

At one point I had it with the constructor taking a length, but then I also needed a different constructor for `set_default`. I could have something with a value and length, but just passing a vector and letting the caller use `rep` was simplest.

2023-12-21 21:42 UTC, plietar commented on src/render_vector.cpp
> +    return Rcpp::XPtr<RenderVector>(new RenderVector(data), true);
`std::vector<double>` had the downside of not supporting `NA`, so I thought we would either need to change the semantics of the class, or do some magic to represent the `NA` somehow, whereas by using a `NumericVector` would avoid having to deal with this.

Looking through the R internals docs just now, it turns out that internally R actually just represents `NA` simply as a NaN with a specific bit pattern, so it might just work even stored in a C++ `double`. I'll give it a try and see if that works

2023-12-21 22:16 UTC, plietar commented on src/RcppExports.cpp
> +        Rf_error("%s", CHAR(rcpp_msgSEXP_gen));
This was introduced by running against a prerelease of Rcpp to avoid a CI failure, as explained in https://github.com/RcppCore/Rcpp/issues/1287#issuecomment-1829886024.

We only need the pre-release to generate this file. Users of the package don't need it.

2023-12-21 22:24 UTC, plietar commented on src/render_vector.cpp
> +    return Rcpp::XPtr<RenderVector>(new RenderVector(data), true);
Alright the `std::vector<double>` worked without any special effort needed, including handling NA values (this is covered by the unit tests). I've switched to that.

2023-12-21 22:44 UTC, plietar commented on R/RcppExports.R
> +    .Call(`_individual_RcppExport_registerCCallable`)
This change comes from an Rcpp change at https://github.com/RcppCore/Rcpp/pull/1256

2023-12-22 10:33 UTC, giovannic approved these changes
This is great thanks!

I would suggest you to have a look at (and extend if you want?) the existing [microbenchmarks](https://github.com/mrc-ide/individual/tree/master/tests/performance). They run a variety of scenarios to show the effects of an improvement in a variety of scenarios, [here's](https://github.com/mrc-ide/individual/issues/154#issuecomment-949018319) an example of how it can be helpful.

2023-12-22 16:44 UTC, plietar commented
Thanks. I've added two microbenchmarks, one which does a single `render()` call and one which calls it as many times as there are timesteps, mimicking the behaviour of a full simulation.

[Rplots.pdf](https://github.com/mrc-ide/individual/files/13754394/Rplots.pdf)

2023-12-22 17:33 UTC, richfitz approved these changes

2023-12-26 13:02 UTC, merged