add prefab for forked transitions
mrc-ide/individual pull request #45
Opened 2021-02-06 22:58 UTC by slwu89

Implement a feature to address issue #40 , adds a new function `fixed_probability_forked_state_change_process` taking the same signature as recommended by @giovannic, also added a new test in test-prefab.R to check the function is working correctly. Currently the sampling of destination state upon leaving is done by linear search (compared to using binary tree or alias tables), which should be fast enough for the small numbers of destination states common in most ABMs.

2021-02-08 09:45 UTC, giovannic requested changes
Thank you, this is great. I've suggested a few changes inline

2021-02-08 09:45 UTC, giovannic commented on src/prefab.cpp
> +            }
We could save on calling R.runif (which is quite expensive) in a loop if we have something like:

```suggestion
            std::vector<size_t> source_individuals(
                target_individuals.begin(),
                target_individuals.end()
            ); //perhaps some less confusing variable names here
            
            // get the indices of source_individuals who leave with only two calls to RNG
            auto leaving_individuals = Rcpp::sample(
              source_individuals.size(),
              Rcpp::rbinom(1, source_individuals.size(), rate)[0], //sample the number of individuals leaving
              false, // replacement
              R_NilValue, // evenly distributed
              false // one based
            )
            
            // then use your lovely CDF
            for (const auto i : leaving_individuals) {        
                double u = random[random_index];           
                auto k_it = std::upper_bound(cdf.begin(),cdf.end(),u);
                int k = std::distance(cdf.begin(),k_it);
                individuals_to_dest[k].emplace_back(source_individuals[i]);
                ++random_index;
            }
```

2021-02-08 09:45 UTC, giovannic commented on tests/testthat/test-prefab.R
> +test_that("fixed_probability_forked_state_change_process works properly", {
Thank you, this test is very concise and clear

2021-02-08 09:45 UTC, giovannic commented on tests/testthat/test-prefab.R
> +  F <- State$new('F', 0)
Could we avoid overriding F, which is short for FALSE?

2021-02-08 19:11 UTC, slwu89 commented on src/prefab.cpp
> +            }
Thanks for the comments! I did not realize `R::runif` was such a performance hit.  I have reworked the function based on your suggestions here https://github.com/mrc-ide/individual/blob/a192e5c336eccaebc3c4596febe91cdc69a87f3d/src/prefab.cpp#L98 (sorry, not sure how to get the nice in-comment code display like you have!)

2021-02-08 19:13 UTC, slwu89 commented on tests/testthat/test-prefab.R
> +  F <- State$new('F', 0)
Good point, I have changed it so it no longer overrides any of R's objects.

2021-02-09 10:18 UTC, giovannic commented on src/prefab.cpp
> +            }
Those fancy in-comment displays are "code suggestions"

>\`\`\`suggestion
> put your code here
> \`\`\`

Multiline suggestions are [brand new](https://github.blog/changelog/2019-10-01-multi-line-references-and-comments-beta/) ;)

Yesss, random number generation looks innocuous but it can [bite back](https://blog.revolutionanalytics.com/2012/08/benchmarking-random-number-generation-from-c.html)

2021-02-09 10:25 UTC, giovannic commented on src/prefab.cpp
> +                individuals_to_dest[dest].emplace_back(individual);
`leaving_individuals` is an integer between 0 and `target_individuals.size()`

What we really want to add to `individuals_to_dest[dest]` is someone from `target_individuals` at position `individual`

This could move someone to `dest` who isn't in `target_individual`

2021-02-09 10:25 UTC, giovannic commented
One small change and we can merge :)

2021-02-09 21:17 UTC, slwu89 commented on src/prefab.cpp
> +                individuals_to_dest[dest].emplace_back(individual);
Thanks @giovannic, yes I overlooked that the index of the bitset that holds people's unique integer id is not always the same as that integer id! That would not be a fun bug to track down later on. I've gone back to the design you originally suggested, copying the bitset elements into a `std::vector<size_t>` object , and then passing the sampled elements of that to `queue_state_update` so that everyone getting moved really was in the `target_individual` object.

2021-02-09 21:21 UTC, slwu89 commented on src/prefab.cpp
> +            }
Interesting! I thought that `R::runif` would be super fast since it was going down to R's C API. If I wanted to draw the random numbers one by one in a fast way in the future, would I include Rmath.h and use `unif_rand`?

2021-02-09 21:31 UTC, slwu89 commented
Thanks for the comments @giovannic! I hope this commit (https://github.com/mrc-ide/individual/pull/45/commits/8af7d00a18fbe9a7e65d2767561d0af36aeda026) fixes that problem of mixing up the index with the actual integer id of the individual in the bitset. 

I had a thought to avoid making the other vector `source_individuals` into which the elements of the bitset are copied, but I don't know enough about the iterators of the IterableBitset object to know if this is more or less efficient (I guess I can just code both and profile it). My thoughts are this:

1. sort the uniformly sampled indices in `leaving_individuals` in ascending order
2. grab an iterator to the beginning of `target_individuals`
3. use `std::advance` with the sorted vector of indices to hop along the `target_individuals` bitset, adding elements to `queue_state_update` as we go.

This would save the creation/destruction of the vector `source_individuals` but I'm not sure if that's a big concern, overall.

2021-02-10 10:41 UTC, giovannic approved these changes

2021-02-10 10:41 UTC, merged

2021-02-10 10:59 UTC, giovannic commented
Yes! Roughly, the vector conversion would be O(bitset.max_size) and sorting would be O(size*log2(size)). But we would need to profile see the improvement in practice.