implement an IntegerVariable class (feat/int_var)
mrc-ide/individual pull request #56
Opened 2021-02-19 00:28 UTC by slwu89

This PR implements an `IntegerVariable` class that largely resembles the `DoubleVariable` class but has a new method, `get_index_of` that returns the indices (as a `Bitset`) of individuals whose values are either in a given set or with a range [a,b]. The PR also includes passing tests to confirm the new class works properly.

2021-02-19 09:24 UTC, giovannic requested changes
This is really useful! I can't wait. A few small requests

2021-02-19 09:24 UTC, giovannic commented on R/integer_variable.R
> +    get_index_of = function(set = NULL, a = NULL, b = NULL) {
:o I love this feature

2021-02-19 09:24 UTC, giovannic commented on R/integer_variable.R
> +        integer_variable_queue_update(
Ah, this causes a bug. I've just fixed it in #55 for DoubleVariable. Could you make a similar update here?

2021-02-19 09:24 UTC, giovannic commented on inst/include/IntegerVariable.h
> +            size_t bset_size = *std::max_element(result_ix.begin(), result_ix.end());
Interesting, the idea here is that we could save space if the indices are small? Kinda nice.

But the issue is that [bitmap bitwise operations require the same sized bitmaps](https://github.com/mrc-ide/individual/blob/dev/inst/include/IterableBitset.h#L239)

And it would be really nice to write something like:

```r
is_infected <- CategoricalVariable$new(...)
risk_level <- IntegerVariable$new(...)
target <- is_infected$get_index_of('yes')$and(risk_level$get_index_of(a=3, b=5))
```

Perhaps it's best to allocate a bitset for all individuals and set the values directly?

2021-02-19 18:50 UTC, slwu89 commented on R/integer_variable.R
> +    get_index_of = function(set = NULL, a = NULL, b = NULL) {
wonderful! It's something I'll need in my future uses for individual.

2021-02-19 19:49 UTC, slwu89 commented on inst/include/IntegerVariable.h
> +            size_t bset_size = *std::max_element(result_ix.begin(), result_ix.end());
Okay, got it. I think I _finally_ understand how bitset works. I've gone ahead and made a change that I think should address this issue: https://github.com/mrc-ide/individual/pull/56/commits/ad8ab82d8bab3544d961fd656a416798198efe69

The returned bitset is initialized with a size equal to that of the number of values held in the IntegerVariable itself.

2021-02-19 19:49 UTC, slwu89 commented on R/integer_variable.R
> +        integer_variable_queue_update(
done! https://github.com/mrc-ide/individual/pull/56/commits/d0ee210550663da2eb1eca7b0b0e1d77bdffea2e# I've confirmed that it is fixed.

2021-02-19 22:01 UTC, slwu89 commented on inst/include/IntegerVariable.h
> +            size_t bset_size = *std::max_element(result_ix.begin(), result_ix.end());
And just confirmed that your example does indeed work correctly!

2021-02-22 09:09 UTC, giovannic approved these changes
Great!

2021-02-22 09:09 UTC, merged