additional prefab transition processes
mrc-ide/individual pull request #63
Opened 2021-02-25 00:53 UTC by slwu89

This PR adds functions `fixed_probability_multinomial_process` and `multi_probability_multinomial_process` which address issues #40 and (partially) #39 , allowing for multinomial processes with constant and individual-specific probability of leaving the source compartment. The individual-specific probability is expected to be contained in a `DoubleVariable` object.

This PR also moves the logic in `bitset_sample` (in bitset.cpp) to `bitset_sample_internal` in IterableBitset.h; this was needed because the prefab transitions in prefab.cpp needed to use that function's logic. It also has a new function `bitset_sample_multi_internal` in IterableBitset.h which samples a bitset with templated input iterators, necessary for `multi_probability_multinomial_process` to work correctly.

Tests for the 2 functions have also been added!

2021-02-26 08:48 UTC, giovannic requested changes
Very nice! Few small nit picks

2021-02-26 08:48 UTC, giovannic commented on src/prefab.cpp
> +    const Rcpp::Environment variable,
Could we instead pass an Rcpp::XPtr<DoubleVariable>?

A few reasons:
 * It adds a bit of type checking
 * I have found incomprehensible errors when I accidentaly put in an R thing that is not what we expect and gets casted into an Rcpp::Environment

Then we could have a small function in R/prefab.R which checks the CategoricalVariable and passes .variable to this function

2021-02-26 08:48 UTC, giovannic commented on src/prefab.cpp
> +    const Rcpp::Environment variable,
Same as above

2021-02-26 08:48 UTC, giovannic commented on src/prefab.cpp
> +    const Rcpp::Environment variable,
same as above

2021-02-26 18:04 UTC, slwu89 commented on src/prefab.cpp
> +    const Rcpp::Environment variable,
Totally. I wasn't sure the best way to pass those data down to C++, this is much better than using Rcpp::Environment.

Fixed in https://github.com/mrc-ide/individual/pull/63/commits/a3cba8683426608a9d8d1969cd68456157b75ac5 and also made `bitset_sample_multi_internal` a little simpler.

2021-03-01 18:20 UTC, giovannic approved these changes
Great, thanks!

2021-03-01 18:20 UTC, merged