Add xor for two bitsets
mrc-ide/individual pull request #76
Opened 2021-03-14 22:46 UTC by slwu89

Being able to do XOR on two bitsets is useful when dealing with complicated divisions of state space, this PR adds (and tests) that functionality.

2021-03-15 18:39 UTC, giovannic requested changes

2021-03-15 18:39 UTC, giovannic commented on src/bitset.cpp
> +    (*a) &= ~(*b);
This appears to implement

```r
a$and(b$not())
```

Which _is_ set difference, but is not _xor_.

Which do you want to implement? Both isn't a bad idea.

To implement xor I would do 
```suggestion
    (*a) ^= *b;
```

To do set difference, I'd add something like this to the Bitset R6 object:

```r
difference = function(other) self$and(other$not())
```

2021-03-15 18:43 UTC, slwu89 commented on src/bitset.cpp
> +    (*a) &= ~(*b);
Oh interesting! Yeah I think both is a good idea. I'll work that one out.

2021-03-16 04:05 UTC, slwu89 commented on src/bitset.cpp
> +    (*a) &= ~(*b);
"xor" properly renamed "set_difference", and proper "xor" added. Included more significant tests for both, for disjoint, identical, and partially overlapping sets.

2021-03-16 09:24 UTC, giovannic approved these changes

2021-03-16 09:24 UTC, merged