get categories of CategoricalVariable
mrc-ide/individual pull request #81
Opened 2021-03-16 17:55 UTC by slwu89

This PR should close out #74

2021-03-16 17:56 UTC, slwu89 commented on src/prefab.cpp
>              const auto random = Rcpp::runif(leaving_individuals.size());
Shoot, sorry @giovannic I just noticed I accidentally pushed this in this PR too (thought it was on a different local branch). Just cleaning up the C++ prefabs a tiny bit.

2021-03-17 09:48 UTC, giovannic requested changes
Great!

2021-03-17 09:48 UTC, giovannic commented on tests/testthat/test-variables.R
> +  )
```suggestion
  expect_setequal(categorical_variable_get_categories(var$.variable), values)
```

2021-03-17 20:45 UTC, giovannic approved these changes

2021-03-17 20:45 UTC, merged